version: 1
policy:
  pullRequests: public
tasks:
  - $if: 'tasks_for == "github-push"'
    then:
      taskId: {$eval: as_slugid("push_task")}
      created: {$fromNow: ''}
      deadline: {$fromNow: '1 hour'}
      provisionerId: aws-provisioner-v1
      workerType: github-worker
      scopes:
        - secrets:get:project/taskcluster/testing/taskcluster-github
      payload:
        maxRunTime: 600
        image: "node:8"
        env:
          DEBUG: "* -babel* -mocha* -nock* -express* -body-parser* -morgan -eslint* -follow-redirects"
          NO_TEST_SKIP: true
        features:
          taskclusterProxy: true
        command:
          - "/bin/bash"
          - "-lc"
          - "git clone ${event.repository.url} repo && cd repo && git checkout ${event.after} && yarn && yarn test"
      metadata:
        name: "Taskcluster GitHub Tests"
        description: "All non-integration tests"
        owner: ${event.pusher.name}@users.noreply.github.com
        source: ${event.repository.url}
